/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.view;



import edu.ijse.controller.BookController;
import edu.ijse.dto.BookDto;
import edu.ijse.homePage.homePage;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class BookView extends javax.swing.JFrame {
private final BookController BOOK_CONTROLLER;
    /**
     * Creates new form BookView
     */
   public BookView() throws Exception {
        BOOK_CONTROLLER = new BookController();
        initComponents();
               setExtendedState(JFrame.MAXIMIZED_BOTH);

           loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblHeader = new javax.swing.JLabel();
        lblBookId = new javax.swing.JLabel();
        lblBookName = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblnumber = new javax.swing.JLabel();
        txtBookId = new javax.swing.JTextField();
        txtBookName = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtnumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblHeader.setFont(new java.awt.Font("Segoe Script", 1, 48)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Manage Books");
        getContentPane().add(lblHeader);
        lblHeader.setBounds(6, 6, 952, 66);

        lblBookId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBookId.setText("Book ID");
        getContentPane().add(lblBookId);
        lblBookId.setBounds(6, 102, 75, 25);

        lblBookName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBookName.setText("Book Name");
        getContentPane().add(lblBookName);
        lblBookName.setBounds(6, 154, 99, 25);

        lblAuthor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAuthor.setText("Author");
        getContentPane().add(lblAuthor);
        lblAuthor.setBounds(6, 205, 70, 25);

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrice.setText("Price");
        getContentPane().add(lblPrice);
        lblPrice.setBounds(417, 154, 84, 25);

        lblnumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblnumber.setText("No Of Books");
        getContentPane().add(lblnumber);
        lblnumber.setBounds(417, 102, 120, 25);
        getContentPane().add(txtBookId);
        txtBookId.setBounds(127, 102, 207, 22);

        txtBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtBookName);
        txtBookName.setBounds(129, 154, 205, 22);
        getContentPane().add(txtAuthor);
        txtAuthor.setBounds(129, 206, 205, 20);
        getContentPane().add(txtPrice);
        txtPrice.setBounds(600, 160, 206, 22);
        getContentPane().add(txtnumber);
        txtnumber.setBounds(600, 100, 206, 22);

        btnSave.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/save new.jpg"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(980, 90, 150, 40);

        btnUpdate.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/update.jpg"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(980, 160, 150, 40);

        btnDelete.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/dlt image.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(980, 230, 150, 47);

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBooksMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBooks);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 271, 964, 318);

        btnBack.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/back image.jpg"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(980, 590, 150, 36);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/background image.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, -4, 1300, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       saveBook();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
updateBook();        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       deleteBook();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setVisible(false);
        new homePage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBooksMouseClicked
        searchBook();
    }//GEN-LAST:event_tblBooksMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblBookId;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblnumber;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtnumber;
    // End of variables declaration//GEN-END:variables
public void clearForm(){
        txtBookId.setText("");
        txtBookName.setText("");
        txtAuthor.setText("");
        txtnumber.setText("");
        txtPrice.setText("");
   }

    private void saveBook() {
        try {
            BookDto dto = new BookDto(txtBookId.getText(), txtBookName.getText(), txtAuthor.getText(),Integer.parseInt(txtnumber.getText()), Double.parseDouble(txtPrice.getText()));
            String resp = BOOK_CONTROLLER.save(dto);
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
              loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    private void updateBook() {
        try {
            BookDto dto = new BookDto(txtBookId.getText(), txtBookName.getText(), txtAuthor.getText(),Integer.parseInt(txtnumber.getText()), Double.parseDouble(txtPrice.getText()));
            String resp = BOOK_CONTROLLER.update(dto);
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void deleteBook() {
        try {
            String resp = BOOK_CONTROLLER.delete(txtBookId.getText());
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
  }

    private void loadTable() {
        try {
            String[] columns = {"BookId", "Name", "Author", "number", "Price"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };
            tblBooks.setModel(dtm);

            ArrayList<BookDto> bookDtos = BOOK_CONTROLLER.getAll();
            for (BookDto bookDto : bookDtos) {
                Object[] rowData = {bookDto.getBookId(), bookDto.getName(), bookDto.getAuthor(), bookDto.getnumber(), bookDto.getPrice()};
                dtm.addRow(rowData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void searchBook() {
        try {
            String code = (String) tblBooks.getValueAt(tblBooks.getSelectedRow(), 0).toString();
            BookDto dto = BOOK_CONTROLLER.get(code);
            if(dto != null){
                txtBookId.setText(dto.getBookId());
                txtBookName.setText(dto.getName());
                txtAuthor.setText(dto.getAuthor());
                txtnumber.setText(dto.getnumber().toString());
                txtPrice.setText(dto.getPrice().toString());
            } else {
                JOptionPane.showMessageDialog(this, "Book not found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    

}