/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.view;

import edu.ijse.controller.BookController;
import edu.ijse.controller.BorrowingTransactionsController;
import edu.ijse.controller.MemberController;
import edu.ijse.dto.BookDto;
import edu.ijse.dto.BorrowDetailDto;
import edu.ijse.dto.BorrowingTransactionsDto;
import edu.ijse.dto.MemberDto;
import edu.ijse.homePage.homePage;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class BorrowingTransactionsView extends javax.swing.JFrame {

    private MemberController memberController;
    private BookController bookController;
    private BorrowingTransactionsController borrowingTransactionsController;
    private ArrayList<BorrowDetailDto> borrowDetailDtos = new ArrayList<>();
    /**
     * Creates new form BorrowingTransactionsView
     */
    public BorrowingTransactionsView() throws Exception {
 this.memberController = new MemberController();
        this.bookController = new BookController();
        this.borrowingTransactionsController = new BorrowingTransactionsController();
        initComponents();
          setExtendedState(JFrame.MAXIMIZED_BOTH);
  loadTable();
    }
 

   
    
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBookSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblBookData = new javax.swing.JTextArea();
        lblMemberId = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtBorrowingId = new javax.swing.JTextField();
        lblBookId = new javax.swing.JLabel();
        txtMemberId = new javax.swing.JTextField();
        txtBookId = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();
        btnMemberSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblMemberData = new javax.swing.JTextArea();
        lblBorrowingId = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBorrowingTransactions = new javax.swing.JTable();
        btnPlace = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnBookSearch.setFont(new java.awt.Font("Script MT Bold", 2, 18)); // NOI18N
        btnBookSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/search.jpg"))); // NOI18N
        btnBookSearch.setText("Search");
        btnBookSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnBookSearch);
        btnBookSearch.setBounds(630, 233, 133, 47);

        lblBookData.setColumns(20);
        lblBookData.setRows(5);
        jScrollPane3.setViewportView(lblBookData);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(810, 220, 234, 86);

        lblMemberId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMemberId.setText("Member ID");
        getContentPane().add(lblMemberId);
        lblMemberId.setBounds(6, 157, 73, 20);

        btnAdd.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/add image.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(630, 340, 132, 30);
        getContentPane().add(txtBorrowingId);
        txtBorrowingId.setBounds(141, 105, 207, 22);

        lblBookId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBookId.setText("Book ID");
        getContentPane().add(lblBookId);
        lblBookId.setBounds(6, 281, 70, 20);

        txtMemberId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtMemberId);
        txtMemberId.setBounds(139, 157, 209, 22);
        getContentPane().add(txtBookId);
        txtBookId.setBounds(125, 282, 206, 20);
        getContentPane().add(txtQty);
        txtQty.setBounds(125, 338, 206, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(6, 199, 1270, 15);

        lblTitle.setFont(new java.awt.Font("Segoe Script", 3, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Place Issued Books");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(6, 6, 837, 66);

        btnMemberSearch.setFont(new java.awt.Font("Script MT Bold", 2, 18)); // NOI18N
        btnMemberSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/search.jpg"))); // NOI18N
        btnMemberSearch.setText("Search");
        btnMemberSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnMemberSearch);
        btnMemberSearch.setBounds(630, 120, 133, 50);

        lblMemberData.setColumns(20);
        lblMemberData.setRows(5);
        jScrollPane1.setViewportView(lblMemberData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(810, 90, 234, 86);

        lblBorrowingId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBorrowingId.setText("Borrowing ID");
        getContentPane().add(lblBorrowingId);
        lblBorrowingId.setBounds(6, 105, 88, 20);

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQty.setText("Qty");
        getContentPane().add(lblQty);
        lblQty.setBounds(6, 338, 23, 20);

        tblBorrowingTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBorrowingTransactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBorrowingTransactionsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBorrowingTransactions);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(6, 391, 837, 145);

        btnPlace.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        btnPlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/download 1.jpg"))); // NOI18N
        btnPlace.setText("Place the Borrwing");
        btnPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlace);
        btnPlace.setBounds(610, 560, 235, 40);

        btnBack.setFont(new java.awt.Font("Script MT Bold", 2, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/back image.jpg"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(920, 560, 154, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("***Books should return within 14 days.***");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 220, 493, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/background image.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-3, -4, 1280, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookSearchActionPerformed
searchBook();       
    }//GEN-LAST:event_btnBookSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addToTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtMemberIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIdActionPerformed

    private void btnMemberSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberSearchActionPerformed
      searchMember();
    }//GEN-LAST:event_btnMemberSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    setVisible(false);
        new homePage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblBorrowingTransactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBorrowingTransactionsMouseClicked
  
    }//GEN-LAST:event_tblBorrowingTransactionsMouseClicked

    private void btnPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceActionPerformed
       Place();
    }//GEN-LAST:event_btnPlaceActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookSearch;
    private javax.swing.JButton btnMemberSearch;
    private javax.swing.JButton btnPlace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea lblBookData;
    private javax.swing.JLabel lblBookId;
    private javax.swing.JLabel lblBorrowingId;
    private javax.swing.JTextArea lblMemberData;
    private javax.swing.JLabel lblMemberId;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblBorrowingTransactions;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtBorrowingId;
    private javax.swing.JTextField txtMemberId;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables

public void searchMember() {
        try {
            String memberId = txtMemberId.getText();
            MemberDto  memberDto =  memberController.get( memberId);
            if ( memberDto != null) {
                lblMemberData.setText( memberDto.getTitle() + " " +  memberDto.getName() + " | " +  memberDto.getAddress());
            } else {
                lblMemberData.setText("Member Not Found");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void searchBook() {
        try {
            String bookId = txtBookId.getText();
            BookDto bookDto = bookController.get(bookId);
            if (bookDto != null) {
                lblBookData.setText(bookDto.getName() + " | " + bookDto.getAuthor()+ " | " + bookDto.getnumber() + " | " + bookDto.getPrice());
            } else {
                lblBookData.setText("Book Not Found");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void addToTable() {
        BorrowDetailDto borrowDetailDto=new BorrowDetailDto();
        borrowDetailDto.setBookId(txtBookId.getText());
        borrowDetailDto.setQty(Integer.parseInt(txtQty.getText()));
        
        borrowDetailDtos.add(borrowDetailDto);
        Object[] rowData={borrowDetailDto.getBookId(),borrowDetailDto.getQty()};
        DefaultTableModel dtm=(DefaultTableModel)tblBorrowingTransactions.getModel();
        dtm.addRow(rowData);
        
        clear();
    }
    
    private void clear(){
       txtBookId.setText("");
       txtQty.setText("");
       lblBookData.setText("");
    }
    
    private void loadTable(){
        String columns[]={"Book Code","Qty"};
        DefaultTableModel dtm =new DefaultTableModel(columns,0){
          public boolean  isCellEditable(int row,int column){
              return false;
          }  
        };
        tblBorrowingTransactions.setModel(dtm);
    }
    

    private void Place() {
        try {
            BorrowingTransactionsDto borrowingTransactionsDto = new BorrowingTransactionsDto();
            borrowingTransactionsDto.setMemberId(txtMemberId.getText());
            borrowingTransactionsDto.setBorrowingId(txtBorrowingId.getText());

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(new Date());
            borrowingTransactionsDto.setDate(date);
 borrowingTransactionsDto.setBorrowDetailDtos(borrowDetailDtos);
SimpleDateFormat sdfDue = new SimpleDateFormat("yyyy-MM-dd");
        
        Date currentDate = new Date();
        
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(currentDate);
        
        calendar.add(Calendar.DAY_OF_MONTH, 12);
        
        Date newDate = calendar.getTime();
        
        String dueDate = sdfDue.format(newDate);
        
        borrowingTransactionsDto.setDueDate(dueDate);

            
            String resp = borrowingTransactionsController.Place(borrowingTransactionsDto);
            JOptionPane.showMessageDialog(this, resp);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    
}

