/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.view;

import edu.ijse.controller.MemberController;
import edu.ijse.dto.MemberDto;
import edu.ijse.homePage.homePage;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */

public class MemberView extends javax.swing.JFrame {
private final MemberController MEMBER_CONTROLLER;
    /**
     * Creates new form MemberViiew
     */
   public MemberView() throws Exception {
        MEMBER_CONTROLLER = new MemberController();
        initComponents();
               setExtendedState(JFrame.MAXIMIZED_BOTH);

         loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPostalCode = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtCity = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        txtMemberId = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        lblHeader = new javax.swing.JLabel();
        lblMemeberId = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtPostalCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblPostalCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPostalCode.setText("Postal Code");
        getContentPane().add(lblPostalCode);
        lblPostalCode.setBounds(478, 237, 77, 20);

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtAddress);
        txtAddress.setBounds(647, 112, 164, 22);

        btnSave.setFont(new java.awt.Font("Script MT Bold", 2, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/save new.jpg"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(506, 308, 120, 40);
        getContentPane().add(txtCity);
        txtCity.setBounds(647, 172, 164, 22);

        btnUpdate.setFont(new java.awt.Font("Script MT Bold", 2, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/update.jpg"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(652, 308, 140, 40);

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAddress.setText("Address");
        getContentPane().add(lblAddress);
        lblAddress.setBounds(478, 112, 77, 20);

        btnDelete.setFont(new java.awt.Font("Script MT Bold", 2, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/dlt image.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(840, 310, 130, 40);

        txtMemberId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtMemberId);
        txtMemberId.setBounds(128, 112, 194, 22);
        getContentPane().add(txtTitle);
        txtTitle.setBounds(128, 172, 194, 22);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(128, 237, 194, 22);

        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });
        getContentPane().add(txtDob);
        txtDob.setBounds(128, 327, 194, 22);

        lblHeader.setFont(new java.awt.Font("Segoe Script", 3, 48)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Member View");
        getContentPane().add(lblHeader);
        lblHeader.setBounds(6, 19, 1024, 50);

        lblMemeberId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMemeberId.setText("MemberId");
        getContentPane().add(lblMemeberId);
        lblMemeberId.setBounds(32, 112, 68, 20);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("Title");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(32, 172, 29, 20);

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Name");
        getContentPane().add(lblName);
        lblName.setBounds(32, 237, 39, 20);

        lblDob.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDob.setText("DOB");
        getContentPane().add(lblDob);
        lblDob.setBounds(32, 327, 29, 20);

        lblCity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCity.setText("City");
        getContentPane().add(lblCity);
        lblCity.setBounds(478, 172, 34, 20);
        getContentPane().add(txtPostalCode);
        txtPostalCode.setBounds(647, 237, 164, 22);

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMemberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMember);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 372, 899, 210);

        btnBack.setFont(new java.awt.Font("Script MT Bold", 2, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/back image.jpg"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(861, 588, 130, 36);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/background image.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, 0, 1310, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
   saveMember();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     deleteMember();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtMemberIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIdActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void tblMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMemberMouseClicked
    searchMember();
    }//GEN-LAST:event_tblMemberMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateMember();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
 setVisible(false);
         new homePage().setVisible(true);    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblMemeberId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPostalCode;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblMember;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtMemberId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPostalCode;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
public void clearForm(){
        txtMemberId.setText("");
        txtTitle.setText("");
        txtName.setText("");
        txtDob.setText("");
        txtAddress.setText("");
        txtCity.setText("");
        txtPostalCode.setText("");        
   }

    private void saveMember() {
        try {
            MemberDto dto = new MemberDto(txtMemberId.getText(), txtTitle.getText(), txtName.getText(),txtDob.getText(),txtAddress.getText(),txtCity.getText(),txtPostalCode.getText());
            String resp = MEMBER_CONTROLLER.save(dto);
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
              loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    private void updateMember() {
        try {
            MemberDto dto = new MemberDto(txtMemberId.getText(), txtTitle.getText(), txtName.getText(),txtDob.getText(),txtAddress.getText(),txtCity.getText(),txtPostalCode.getText());
            String resp = MEMBER_CONTROLLER.update(dto);
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void deleteMember() {
        try {
            String resp = MEMBER_CONTROLLER.delete(txtMemberId.getText());
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
  }

    private void loadTable() {
        try {
            String[] columns = {"MemberId","Title", "Name", "Dob", "Address", "City","PostalCode"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };
            tblMember.setModel(dtm);

            ArrayList<MemberDto> memberDtos = MEMBER_CONTROLLER.getAll();
            for (MemberDto memberDto : memberDtos) {
                Object[] rowData = {memberDto.getMemberId(), memberDto.getTitle(), memberDto.getName(), memberDto.getDob(), memberDto.getAddress(), memberDto.getCity(), memberDto.getPostalCode()};
                dtm.addRow(rowData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void searchMember() {
        try {
            String code = (String) tblMember.getValueAt(tblMember.getSelectedRow(), 0).toString();
            MemberDto dto = MEMBER_CONTROLLER.get(code);
            if(dto != null){
                txtMemberId.setText(dto.getMemberId());
                txtTitle.setText(dto.getTitle());
                txtName.setText(dto.getName());
                 txtDob.setText(dto.getDob());
                  txtAddress.setText(dto.getAddress());
                   txtCity.setText(dto.getCity());
                    txtPostalCode.setText(dto.getPostalCode());
              
            } else {
                JOptionPane.showMessageDialog(this, "Member not found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    

}