/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.view;

import edu.ijse.controller.BookController;
import edu.ijse.controller.BorrowingTransactionsController;
import edu.ijse.controller.MemberController;
import edu.ijse.controller.ReturnController;

import edu.ijse.dto.BookDto;
import edu.ijse.dto.MemberDto;
import edu.ijse.dto.ReturnDetailDto;
import edu.ijse.dto.ReturnDto;
import edu.ijse.homePage.homePage;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class ReturnView extends javax.swing.JFrame {
   private MemberController memberController;
    private BookController bookController;
     private ReturnController returnController;
    private BorrowingTransactionsController borrowingTransactionsController;
    private ArrayList<ReturnDetailDto> returnDetailDtos = new ArrayList<>();
    /**
     * Creates new form ReturnView
     */
    public ReturnView() {
         this.memberController = new MemberController();
        this.bookController = new BookController();
        this.borrowingTransactionsController = new BorrowingTransactionsController();
        this.returnController = new ReturnController();
        initComponents();
         setExtendedState(JFrame.MAXIMIZED_BOTH);
           loadTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopic = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtFine = new javax.swing.JTextField();
        lblFine = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnMemberSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblMemberData = new javax.swing.JTextArea();
        lblBookId = new javax.swing.JLabel();
        btnBookSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblBookData = new javax.swing.JTextArea();
        lblMemberId = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtMemberId = new javax.swing.JTextField();
        javax.swing.JLabel lblReturnId = new javax.swing.JLabel();
        txtBorrowingId = new javax.swing.JTextField();
        txtReturnId = new javax.swing.JTextField();
        lblBorrowingID = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        btnBorrowingIdSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblBorrowingData = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        txtQty = new javax.swing.JTextField();
        btnPlace = new javax.swing.JButton();
        txtBookId = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblReturn = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTopic.setFont(new java.awt.Font("Segoe Script", 3, 48)); // NOI18N
        lblTopic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopic.setText("Return & Apply Fines");
        getContentPane().add(lblTopic);
        lblTopic.setBounds(10, 10, 994, 60);

        btnBack.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/back image.jpg"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(816, 592, 110, 40);
        getContentPane().add(txtFine);
        txtFine.setBounds(234, 473, 227, 22);

        lblFine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFine.setText("Apply Fines");
        getContentPane().add(lblFine);
        lblFine.setBounds(25, 475, 76, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(6, 442, 1250, 10);

        btnMemberSearch.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        btnMemberSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/search.jpg"))); // NOI18N
        btnMemberSearch.setText("Search");
        btnMemberSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnMemberSearch);
        btnMemberSearch.setBounds(29, 292, 130, 47);

        lblMemberData.setColumns(20);
        lblMemberData.setRows(5);
        jScrollPane1.setViewportView(lblMemberData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 284, 234, 86);

        lblBookId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBookId.setText("Book ID");
        getContentPane().add(lblBookId);
        lblBookId.setBounds(586, 244, 53, 20);

        btnBookSearch.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        btnBookSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/search.jpg"))); // NOI18N
        btnBookSearch.setText("Search");
        btnBookSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnBookSearch);
        btnBookSearch.setBounds(562, 294, 130, 50);

        lblBookData.setColumns(20);
        lblBookData.setRows(5);
        jScrollPane3.setViewportView(lblBookData);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(757, 284, 234, 86);

        lblMemberId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMemberId.setText("Member ID");
        getContentPane().add(lblMemberId);
        lblMemberId.setBounds(29, 244, 73, 20);

        btnAdd.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/add image.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(574, 449, 110, 40);
        getContentPane().add(txtMemberId);
        txtMemberId.setBounds(230, 244, 234, 22);

        lblReturnId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReturnId.setText("Return ID");
        getContentPane().add(lblReturnId);
        lblReturnId.setBounds(29, 160, 70, 20);

        txtBorrowingId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBorrowingIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtBorrowingId);
        txtBorrowingId.setBounds(235, 160, 209, 22);
        getContentPane().add(txtReturnId);
        txtReturnId.setBounds(235, 122, 206, 20);

        lblBorrowingID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBorrowingID.setText("Boorowing ID");
        getContentPane().add(lblBorrowingID);
        lblBorrowingID.setBounds(29, 121, 91, 20);

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQty.setText("Quantity");
        getContentPane().add(lblQty);
        lblQty.setBounds(29, 413, 57, 20);

        btnBorrowingIdSearch.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        btnBorrowingIdSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/search.jpg"))); // NOI18N
        btnBorrowingIdSearch.setText("Search");
        btnBorrowingIdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowingIdSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrowingIdSearch);
        btnBorrowingIdSearch.setBounds(500, 110, 130, 50);

        lblBorrowingData.setColumns(20);
        lblBorrowingData.setRows(5);
        jScrollPane2.setViewportView(lblBorrowingData);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(675, 96, 234, 86);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 223, 1000, 3);
        getContentPane().add(txtQty);
        txtQty.setBounds(230, 414, 234, 22);

        btnPlace.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        btnPlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/download 1.jpg"))); // NOI18N
        btnPlace.setText("Place");
        btnPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlace);
        btnPlace.setBounds(654, 592, 130, 42);
        getContentPane().add(txtBookId);
        txtBookId.setBounds(757, 244, 234, 22);

        tblReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReturnMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblReturn);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(25, 513, 611, 136);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/background image.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      setVisible(false);
        new homePage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMemberSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberSearchActionPerformed
        searchMember();
    }//GEN-LAST:event_btnMemberSearchActionPerformed

    private void btnBookSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookSearchActionPerformed
        searchBook();
    }//GEN-LAST:event_btnBookSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addToTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtBorrowingIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBorrowingIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBorrowingIdActionPerformed

    private void btnBorrowingIdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowingIdSearchActionPerformed
      searchBorrow();
    }//GEN-LAST:event_btnBorrowingIdSearchActionPerformed

    private void btnPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceActionPerformed
Place();   
    }//GEN-LAST:event_btnPlaceActionPerformed

    private void tblReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReturnMouseClicked
    }//GEN-LAST:event_tblReturnMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookSearch;
    private javax.swing.JButton btnBorrowingIdSearch;
    private javax.swing.JButton btnMemberSearch;
    private javax.swing.JButton btnPlace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea lblBookData;
    private javax.swing.JLabel lblBookId;
    private javax.swing.JTextArea lblBorrowingData;
    private javax.swing.JLabel lblBorrowingID;
    private javax.swing.JLabel lblFine;
    private javax.swing.JTextArea lblMemberData;
    private javax.swing.JLabel lblMemberId;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JTable tblReturn;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtBorrowingId;
    private javax.swing.JTextField txtFine;
    private javax.swing.JTextField txtMemberId;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtReturnId;
    // End of variables declaration//GEN-END:variables
public void searchMember() {
        try {
            String memberId = txtMemberId.getText();
            MemberDto  memberDto =  memberController.get( memberId);
            if ( memberDto != null) {
                lblMemberData.setText( memberDto.getTitle() + " " +  memberDto.getName() + " | " +  memberDto.getAddress());
            } else {
                lblMemberData.setText("Member Not Found");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void searchBook() {
        try {
            String bookId = txtBookId.getText();
            BookDto bookDto = bookController.get(bookId);
            if (bookDto != null) {
                lblBookData.setText(bookDto.getName() + " | " + bookDto.getAuthor()+ " | " + bookDto.getnumber() + " | " + bookDto.getPrice());
            } else {
                lblBookData.setText("Book Not Found");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void addToTable() {
       ReturnDetailDto returnDetailDto=new ReturnDetailDto();
        returnDetailDto.setBookId(txtBookId.getText());
        returnDetailDto.setQty(Integer.parseInt(txtQty.getText()));
        
      
                returnDetailDtos.add(returnDetailDto);

        Object[] rowData={returnDetailDto.getBookId(),returnDetailDto.getQty()};
        DefaultTableModel dtm=(DefaultTableModel)tblReturn.getModel();
        dtm.addRow(rowData);
        
        clear();
    }
    
    private void clear(){
       txtBookId.setText("");
       txtQty.setText("");
       lblMemberData.setText("");
    }
    
    private void loadTable(){

        String columns[]={"Book Id","Qty"};
        DefaultTableModel dtm =new DefaultTableModel(columns,0){
          public boolean  isCellEditable(int row,int column){
              return false;
          }  
        };
        tblReturn.setModel(dtm);
        
    }
    
    

    private void Place() {
        try{
            ReturnDto returnDto=new ReturnDto();
            returnDto.setMemberId(txtMemberId.getText());
            returnDto.setReturnId(txtReturnId.getText());
            
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String date=sdf.format(new Date());
            returnDto.setDate(date);          
           
            returnDto.setReturnDetailDtos(returnDetailDtos);
            
            returnDto.setFine(Double.parseDouble(txtFine.getText()));
            
            String resp=returnController.Place(returnDto);
            JOptionPane.showMessageDialog(this,resp);
            
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
     private void searchBorrow(){
        try{
                  
              String id=txtReturnId.getText();
              String borrow=borrowingTransactionsController.gets(id);
              if(borrow!=null){
                  lblBorrowingData.setText(borrow);                       
        
    String returnDateString = lblBorrowingData.getText();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    LocalDate returnDate = LocalDate.parse(returnDateString, formatter);
    LocalDate currentDate = LocalDate.now();
    long daysBetween = ChronoUnit.DAYS.between(returnDate, currentDate);
    double fine ;
    if(daysBetween<=14){
        fine=0;
    }else{
         fine = (daysBetween-14) * 5;
    }
txtFine.setText(String.valueOf(fine));
                  
              }else{
                  lblBorrowingData.setText("Book can not found");
              }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
     
}

